# Generated by Django 2.1 on 2020-04-03 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousFutures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('symbol', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='code',
            name='root_symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='futures.ContinuousFutures'),
        ),
    ]
