# Generated by Django 3.0.4 on 2020-04-03 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0003_auto_20200403_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='root_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futures.ContinuousFutures'),
        ),
        migrations.AlterField(
            model_name='continuousfutures',
            name='exchange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='futures.Exchange'),
            preserve_default=False,
        ),
    ]
