# Generated by Django 3.0.4 on 2020-04-03 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0005_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roll',
            name='roll_type',
        ),
    ]
