# Generated by Django 3.0.4 on 2020-04-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0006_remove_roll_roll_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roll',
            name='ver',
        ),
        migrations.AddField(
            model_name='roll',
            name='verion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
