# Generated by Django 3.0.4 on 2020-04-05 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0008_auto_20200404_1314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Code',
            new_name='Contract',
        ),
        migrations.RenameModel(
            old_name='Bar',
            new_name='DailyBar',
        ),
        migrations.RenameModel(
            old_name='ContinuousFutures',
            new_name='RootSymbol',
        ),
        migrations.AlterModelTable(
            name='exchange',
            table='exchange',
        ),
    ]
