# Generated by Django 3.0.4 on 2020-04-05 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0009_auto_20200405_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailybar',
            old_name='code',
            new_name='contract',
        ),
        migrations.RenameField(
            model_name='roll',
            old_name='code',
            new_name='contract',
        ),
    ]
