# Generated by Django 3.0.5 on 2020-04-26 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0010_auto_20200405_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinuteBar',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('open_interest', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='futures.Contract')),
            ],
        ),
        migrations.DeleteModel(
            name='Roll',
        ),
    ]
