# Generated by Django 2.1 on 2020-04-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0010_auto_20200405_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roll',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='roll',
            name='root_symbol',
        ),
        migrations.DeleteModel(
            name='Roll',
        ),
    ]
