# Generated by Django 3.0.5 on 2020-04-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0011_auto_20200426_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='multiplier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='tick_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
