# Generated by Django 3.0.5 on 2020-04-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0012_auto_20200426_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='symbol_temp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
