# Generated by Django 3.0.5 on 2020-04-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0013_contract_symbol_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
