# Generated by Django 2.1 on 2020-04-27 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0015_rootsymbol_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinuteBarChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('datetime_temp', models.BigIntegerField()),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('open_interest', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='minutebar',
            index=models.Index(fields=['contract', 'datetime'], name='futures_min_contrac_50c0e8_idx'),
        ),
        migrations.AddField(
            model_name='minutebarchange',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futures.Contract'),
        ),
    ]
