# Generated by Django 2.1 on 2020-04-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0016_auto_20200427_1328'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='minutebar',
            name='futures_min_contrac_50c0e8_idx',
        ),
        migrations.AlterUniqueTogether(
            name='minutebar',
            unique_together={('contract', 'datetime')},
        ),
        migrations.AlterModelTable(
            name='minutebarchange',
            table='futures_minutebar_changes',
        ),
    ]
