# Generated by Django 3.0.5 on 2020-04-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0018_auto_20200427_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailybar',
            options={'get_latest_by': 'datetime'},
        ),
        migrations.AlterModelOptions(
            name='minutebar',
            options={'get_latest_by': 'datetime'},
        ),
    ]
