# Generated by Django 3.0.5 on 2020-05-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0019_auto_20200427_1224'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailybar',
            unique_together={('contract', 'datetime')},
        ),
        migrations.AddIndex(
            model_name='dailybar',
            index=models.Index(fields=['datetime'], name='daybar_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='minutebar',
            index=models.Index(fields=['datetime'], name='minbar_dt_idx'),
        ),
    ]
