# Generated by Django 3.0.5 on 2020-05-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0021_continuousfutures'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootsymbol',
            name='launched',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
