# Generated by Django 2.1 on 2020-05-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0022_rootsymbol_launched'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContinuousFutures',
            new_name='Chain',
        ),
    ]
