# Generated by Django 2.1 on 2020-05-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0023_auto_20200530_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootsymbol',
            name='commission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rootsymbol',
            name='commission_type',
            field=models.CharField(choices=[('f', 'Fixed'), ('p', 'Percent')], default='f', max_length=1),
        ),
        migrations.AddField(
            model_name='rootsymbol',
            name='margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rootsymbol',
            name='multiplier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rootsymbol',
            name='tick_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
