# Generated by Django 2.1 on 2020-05-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0026_dailybarchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailybar',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='dailybar',
            name='date_updated',
        ),
    ]
