# Generated by Django 3.0.6 on 2020-06-02 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0027_auto_20200530_1734'),
        ('stocks', '0002_auto_20200602_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='futures.Exchange'),
        ),
    ]
