# Generated by Django 3.0.6 on 2020-06-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20200602_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
