# Generated by Django 2.1 on 2020-06-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_code_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='wind_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
