# Generated by Django 2.1 on 2020-06-03 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_code_wind_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'adjustment factor'), (1, 'dividends'), (2, 'splits')], default=0)),
                ('datetime', models.DateTimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Code')),
            ],
            options={
                'ordering': ('datetime',),
                'get_latest_by': 'datetime',
            },
        ),
    ]
