# Generated by Django 2.1 on 2020-06-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='market',
            field=models.IntegerField(blank=True, choices=[(0, '主板'), (1, '中小企业板'), (2, '创业板'), (3, '科创板')], null=True),
        ),
    ]
