# Generated by Django 2.1 on 2020-06-03 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_code_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybar',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Code'),
        ),
        migrations.AlterUniqueTogether(
            name='daybar',
            unique_together={('code', 'datetime')},
        ),
    ]
